version: "3"


services:
  postgresdb:
    build:
      context: ./docker/postgresdb
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=123321
    volumes:
      - ./docker/postgresdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5433"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "8001:8001"
    depends_on:
      - postgresdb

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - postgresdb
    ports:
      - "80:80"
    volumes:
      - ./static/:/static